### ISSUE TITLE
New Logic for create an edit event on inner table

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#632]
**Is your feature request related to a problem? Please describe.**
it is not possible to use @ViewChild of ng-template content, since @ViewChild only works on current html template

see explanation here - https://blog.angular-university.io/angular-viewchild/

![image](https://user-images.githubusercontent.com/86002958/169285565-c8663397-d5d7-406c-a9c5-946d9c000bb4.png)

**Describe the solution you'd like**
a new logic to create an edit event on inner table

**Describe alternatives you've considered**

I tried the following suggestions they dont works

https://stackoverflow.com/questions/58340734/how-to-reference-ng-template-in-component

https://stackoverflow.com/questions/47428783/get-reference-to-element-inside-ng-template/47429410#47429410

**Comment by israelComrax** [comment]
its a serious issue i didnt manage to solve it yet

**Comment by israelComrax** [comment]
it works also on nested tables. the problems are
1. if its not open the template isnt in the view therefor it dosent exist.
2. if we have a few open so we need to know which one is it
solution
1. doing the stuff after the opening (we need settimeout since it shows only afterviewinit)
2. having viewchildren and then finding by index or something
