### ISSUE TITLE
kkl-ngx-table - pagination style on mobile

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#674]
**Describe the bug**
in mobile, that style of the pginatio inot working.

**To Reproduce**
1. create kkl-ngx-local-table and kkl-local-table
2. add pagination
3. switch to mobile
4. hide/show kkl-local-table

**Expected behavior**
![image](https://user-images.githubusercontent.com/86002958/170208407-79755815-cc93-481e-aa69-0c7be91f0890.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/86002958/170208302-4ec6c38f-f5b1-4983-b9b0-ce82b6125a1b.png)

**Comment by RamComrax** [comment]
First of all, thank you for noticing and notifying about the problem.
This has probably happened due to the many changes that have occurred lately with the new ngx table and the fact that many people have worked on the same .scss file.
I have rearranged the .scss file and included the selectors of the footer in their right place at all breakpoint.
mobile:
![mobile_paginator_aligned](https://user-images.githubusercontent.com/97685690/170479152-bb2c2b37-4e48-486b-9644-18243498c83d.png)
tablet:
![tablet_paginator_aligned](https://user-images.githubusercontent.com/97685690/170479378-cf282027-b2f9-461d-8fae-43456a2e64d3.png)
desktop:
![desktop_paginator_aligned](https://user-images.githubusercontent.com/97685690/170479523-e56672ae-0036-446b-95ad-5817d3c07347.png)
