### ISSUE TITLE
kkl-ngx-table - inputs ui  on tablet 

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#716]
**Describe the bug**
Inputs ui are incorrenct

**Screenshots - Tablet ui**
![image](https://user-images.githubusercontent.com/86002958/172335009-5b87830b-13e6-420e-9c02-209c3f0f2fb7.png)

**Screenshots - Inner table ob Tablet ui**
![image](https://user-images.githubusercontent.com/86002958/172335379-512396ae-c5f0-4130-adf2-bdea413f2998.png)

**Comment by israelComrax** [comment]
@RamComrax  you fixed it?
it looks like you did.
confirm and close.

**Comment by RamComrax** [comment]
I have delt with this issue before.
Due to the fact that we are copying and pasting the table every time we use it, these kind of issues are likely to repet themselves.
I recomend that you would update your local comrax-components-demo project and copy the HTML and CSS files from complex-ngx-table component; These two files represent the most up to date version of the table.
If your issue remains after you have done these steps, I recomend fixing the issue locally in your own project, it is probably due to an additional or a missing 'direction' somewhere in your project affecting the layout of these edit field inputs.
If you don't manage to solve the issue, plese re-open it, so we would be able to have a thorough look at this
