### ISSUE TITLE
kkl-ngx-table - multi render of expandTemaplte

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#719]
**Describe the bug**
ngOnInit of comp that is render inside renderTemplate is called 3 times

**To Reproduce**
1. create ngx table
2. create comp 
3. add console.log in ngOnInut
4. implment the comp as expandTemplate
5. open expandTemplate
6. comment expendTemplate of mobile/tablet - the number of the logs decresse

**Expected behavior**
ngOnOnit will be called one - only form the cuurent ui - desktop, mobile or tablet

**Screenshots**

**Possible Soluation**
hide tablet and mobile ui with ngIf

**Comment by israelComrax** [comment]
you probably right. it was done with hidden for 2 reasons
1. because i needed the ngx-table to be all the time in the view since expand is done within it so if theres a change it sould imply also there. 
2. because ngx-table did it that way and i wanted them to have it the same.
so anyway you can definitely change it.

**Comment by israelComrax** [comment]
i think its ok so i will close
